#!/usr/bin/env python3

'''
The programs in this library are for finding overlapping clusters of LSVs to be used for SVR formulation
 prior to co-splicing network inference. Data comes from TSV files generated by MAJIQ framework.
'''

import argparse

# Get most up and downstream positions of current LSV (and sort)
def get_lsv_boundary(coords):

    positions = []
  
    for j in coords:
        pos = j.split('-')
        positions.append(int(pos[0]))
        positions.append(int(pos[1]))

    sorted_positions = sorted(positions)

    return (sorted_positions[0], sorted_positions[-1])

# Parse LSVs and collect their junction coordinates
#   Group by gene
def get_lsv_coords(lsv_recs):

    gene_dict = {}

    for rec in lsv_recs.values():
        gene = rec[1]
        if gene not in gene_dict:
            gene_dict[gene] = {}
        lsv = rec[2]
        jCoords = rec[14].split(';')
        # Add intron junction if LSV contains intron retention event
        ir = rec[16]
        if ir != '':
            jCoords.append(ir)
        gene_dict[gene][lsv] = get_lsv_boundary(jCoords) 

    return gene_dict

# Group any overlapping LSVs into eventual SVRs
def merge_lsv_coordinates(intervals):

    sorted_by_lower_bound = sorted(intervals, key=lambda tup: tup[0])
    merged = []

    for higher in sorted_by_lower_bound:
        if not merged:
            merged.append(higher)
        else:
            lower = merged[-1]
            # test for intersection between lower and higher:
            # we know via sorting that lower[0] <= higher[0]
            if higher[0] <= lower[1]:
                upper_bound = max(lower[1], higher[1])
                merged[-1] = (lower[0], upper_bound)  # replace by merged interval
            else:
                merged.append(higher)

    return merged

# For each gene, collect and merge overlapping LSVs
def gene_clusters(gene, lsv_set):

    # Define cluster regions first 
    cluster_coords = sorted(merge_lsv_coordinates([coords for coords in lsv_set.values()]))

    cluster_dict = {}

    n = 1
    for cluster in cluster_coords:
        cluster_dict[cluster] = gene + '_cluster_' + str(n)
        n = n + 1

    lsv_to_clust = {}

    # Parse lsvs
    for lsv,lsv_coords in lsv_set.items():
        s,e = lsv_coords[0], lsv_coords[1]
        # Parse cluster coordinates and see if lsv falls within them
        for clust_coords in cluster_coords:
            cS, cE = clust_coords[0], clust_coords[1]
            # When found, indicate in dictionary which cluster it belongs to
            if s >= cS and e <= cE:
                lsv_to_clust[lsv] = cluster_dict[clust_coords]
                break

    return lsv_to_clust    

# Parse gene dictionary and start looking for potential SVRs
def get_lsv_clusters(gene_dict):

    lsv_clusters = {}

    for gene,lsvs in gene_dict.items():
        for lsv,cluster in gene_clusters(gene, lsvs).items():
            lsv_clusters[lsv] = cluster

    return lsv_clusters


